services:
  db:
    container_name: csr-postgres-container
    image: postgres:16.4
    env_file:
      - ./src/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: